USE shopping_cart_localization;

INSERT INTO localization_strings (`key`, value, language) VALUES
-- English
('select.language', 'Select the language:', 'en_US'),
('confirm.language', 'Confirm Language', 'en_US'),
('enter.num.items', 'Enter number of items:', 'en_US'),
('num.items.prompt', 'Number of items', 'en_US'),
('enter.items.btn', 'Enter Items', 'en_US'),
('enter.price', 'Enter price for item', 'en_US'),
('price.prompt', 'Price', 'en_US'),
('enter.quantity', 'Enter quantity for item', 'en_US'),
('quantity.prompt', 'Quantity', 'en_US'),
('calculate.btn', 'Calculate Total', 'en_US'),
('total.cost', 'Total cost:', 'en_US'),
('error.invalid.number', 'Please enter a valid number of items.', 'en_US'),
('error.invalid.input', 'Please enter valid price and quantity values.', 'en_US'),

-- Finnish
('select.language', 'Valitse kieli:', 'fi_FI'),
('confirm.language', 'Vahvista kieli', 'fi_FI'),
('enter.num.items', 'Syötä ostettavien tuotteiden määrä:', 'fi_FI'),
('num.items.prompt', 'Määrä', 'fi_FI'),
('enter.items.btn', 'Syötä tuotteet', 'fi_FI'),
('enter.price', 'Syötä tuotteen hinta', 'fi_FI'),
('price.prompt', 'Hinta', 'fi_FI'),
('enter.quantity', 'Syötä tuotteen määrä', 'fi_FI'),
('quantity.prompt', 'Määrä', 'fi_FI'),
('calculate.btn', 'Laske kokonaishinta', 'fi_FI'),
('total.cost', 'Kokonaishinta:', 'fi_FI'),
('error.invalid.number', 'Anna kelvollinen tuotteiden määrä.', 'fi_FI'),
('error.invalid.input', 'Anna kelvolliset hinta- ja määräarvot.', 'fi_FI'),

-- Swedish
('select.language', 'Välj språk:', 'sv_SE'),
('confirm.language', 'Bekräfta språk', 'sv_SE'),
('enter.num.items', 'Ange antalet varor att köpa:', 'sv_SE'),
('num.items.prompt', 'Antal', 'sv_SE'),
('enter.items.btn', 'Ange varor', 'sv_SE'),
('enter.price', 'Ange priset för varan', 'sv_SE'),
('price.prompt', 'Pris', 'sv_SE'),
('enter.quantity', 'Ange mängden varor', 'sv_SE'),
('quantity.prompt', 'Mängd', 'sv_SE'),
('calculate.btn', 'Beräkna totalkostnad', 'sv_SE'),
('total.cost', 'Total kostnad:', 'sv_SE'),
('error.invalid.number', 'Ange ett giltigt antal varor.', 'sv_SE'),
('error.invalid.input', 'Ange giltiga pris- och mängdvärden.', 'sv_SE'),

-- Japanese
('select.language', '言語を選んでください：', 'ja_JP'),
('confirm.language', '言語を確認', 'ja_JP'),
('enter.num.items', '購入する商品の数を入力してください：', 'ja_JP'),
('num.items.prompt', '数量', 'ja_JP'),
('enter.items.btn', '商品を入力', 'ja_JP'),
('enter.price', '商品の価格を入力してください', 'ja_JP'),
('price.prompt', '価格', 'ja_JP'),
('enter.quantity', '商品の数量を入力してください', 'ja_JP'),
('quantity.prompt', '数量', 'ja_JP'),
('calculate.btn', '合計金額を計算', 'ja_JP'),
('total.cost', '合計金額：', 'ja_JP'),
('error.invalid.number', '有効な商品数を入力してください。', 'ja_JP'),
('error.invalid.input', '有効な価格と数量の値を入力してください。', 'ja_JP'),

-- Arabic
('select.language', 'اختر اللغة:', 'ar_AR'),
('confirm.language', 'تأكيد اللغة', 'ar_AR'),
('enter.num.items', 'أدخل عدد العناصر:', 'ar_AR'),
('num.items.prompt', 'العدد', 'ar_AR'),
('enter.items.btn', 'إدخال العناصر', 'ar_AR'),
('enter.price', 'أدخل سعر العنصر', 'ar_AR'),
('price.prompt', 'السعر', 'ar_AR'),
('enter.quantity', 'أدخل كمية العنصر', 'ar_AR'),
('quantity.prompt', 'الكمية', 'ar_AR'),
('calculate.btn', 'حساب التكلفة الإجمالية', 'ar_AR'),
('total.cost', 'التكلفة الإجمالية:', 'ar_AR'),
('error.invalid.number', 'الرجاء إدخال عدد صحيح من العناصر.', 'ar_AR'),
('error.invalid.input', 'الرجاء إدخال قيم صحيحة للسعر والكمية.', 'ar_AR');